package com.marbl.warehouse.gui;

import com.marbl.warehouse.domain.Klant;
import com.marbl.warehouse.domain.Onderdeel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class JFrameVerwijderen extends javax.swing.JFrame implements ActionListener {

    JComboBox jCbSelect;
    ArrayList<Component> componenten;
    ArrayList<Klant> klanten;
    ArrayList<Onderdeel> onderdelen;
    String soort;
    Magazijn main;

    /**
     * Creates new form JFrameVerwijderen met ingevoerde waardes.
     */
    public JFrameVerwijderen(String soort, Collection<Onderdeel> onderdelen, Collection<Klant> klanten, Magazijn main) {
        initComponents();

        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setTitle("Onderdeel:");
        this.main = main;
        this.setLocation(400, 250);
        jBtClose.setText("Sluit Venster");
        componenten = new ArrayList<>();
        jCbSelect = new JComboBox();
        jCbSelect.setBounds(20, 20, 200, 20);

        add(jCbSelect);
        JButton button = new JButton("Verwijder");
        button.addActionListener(this);
        button.setBounds(70, 100, 100, 30);
        button.setActionCommand("Button verwijderen.");
        add(button);

        this.soort = soort;
        this.onderdelen = new ArrayList<Onderdeel>(onderdelen);
        this.klanten = new ArrayList<Klant>(klanten);
        switch (soort) {
            case "Klant": {
                for (Klant kl : klanten) {
                    jCbSelect.addItem(Integer.toString(kl.getCode()) + ":   " + kl.getNaam());
                }
                break;
            }
            case "Onderdeel": {
                for (Onderdeel ond : onderdelen) {
                    jCbSelect.addItem(Integer.toString(ond.getCode()) + ":   " + ond.getOmschrijving());
                }
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.marbl.warehouse.MagazijnApplicatieApp.class).getContext().getResourceMap(JFrameVerwijderen.class);
        jBtClose.setText(resourceMap.getString("jBtClose.text")); // NOI18N
        jBtClose.setName("jBtClose"); // NOI18N
        jBtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtClose, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jBtClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * De methode die wordt aangeroepen als het form geclosed moet worden. de
     * setVisible(true) van het hoofdmenu wordt aangeroepen en dit form wordt
     * gedisposed.
     *
     * @param evt Het event
     */
    private void jBtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCloseActionPerformed
        main.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtCloseActionPerformed

    /**
     * De methode die wordt aangeroepen als een button wordt gepressed.
     *
     * @param e Het even
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            switch (soort) {
                case "Onderdeel": {
                    int index = jCbSelect.getSelectedIndex();
                    main.getDatabase().deleteOnderdeel(onderdelen.get(index).getCode());
                    JOptionPane.showMessageDialog(this, "Het Onderdeel is correct verwijderd.", "Gelukt!", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    this.dispose();
                    main.setVisible(true);
                    break;
                }
                case "Klant": {
                    int index = jCbSelect.getSelectedIndex();
                    main.getDatabase().deleteKlant(klanten.get(index).getCode());
                    JOptionPane.showMessageDialog(this, "De klant is correct verwijderd.", "Gelukt!", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    this.dispose();
                    main.setVisible(true);
                    break;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Fout", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtClose;
    // End of variables declaration//GEN-END:variables
}
